dmirano/4509-outcomes-and-metrics-help-text
Enterprise-CMCS/eAPD pull request #4536
Opened 2023-02-10 19:01 UTC by mirano-darren

Resolves #4509 

### Description
Changes the help text for the outcomes and metrics page for mmis only.

### Significant changes or possible side effects
Only affects outcomes.js and the corresponding yaml file

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |

### Steps to manually verify this change

1. Verify HITECH has old help text
2. Verify MMIS has the new help text

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2023-02-13 13:41 UTC, tbolt approved these changes

2023-02-14 19:47 UTC, thetif approved these changes

2023-02-14 19:47 UTC, thetif commented on web/src/pages/apd/activities/oms/Outcomes.test.js
> +          apdType: 'HITECH',
you should use the APD_TYPE.HITECH const here

2023-02-14 19:47 UTC, thetif commented on web/src/pages/apd/activities/oms/Outcomes.test.js
> +      apdType: 'HITECH',
you should use the APD_TYPE.HITECH const here

2023-02-15 17:09 UTC, jeromeleecms requested changes
Can you make the link to the CMS certification repository open in a new tab? Everything else looks good!

2023-02-16 00:14 UTC, jeromeleecms approved these changes
Looks good!

2023-02-16 20:16 UTC, SGilliamA1M approved these changes
Looks good!

2023-02-17 14:40 UTC, merged