Dmirano/4510 state staff and expenses help text
Enterprise-CMCS/eAPD pull request #4546
Opened 2023-02-14 19:10 UTC by mirano-darren

Resolves #4510 

### Description
Updates help text for the mmis state staff and expenses page

### Significant changes or possible side effects
None, all changes isolated to state staff and expenses page

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |

### Steps to manually verify this change

1. Open a HITECH APD and verify the state staff and expenses has the old help text
2. Open a MMIS APD and verify the state staff and expenses has the new help text

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2023-02-14 19:40 UTC, thetif approved these changes

2023-02-14 19:40 UTC, thetif commented on web/src/pages/apd/activities/state-costs/NonPersonnelCosts.test.js
> +    ).toEqual({ expenses: 'these are expenses', apdType: 'HITECH' });
you should use the APD_TYPE.HITECH const here

2023-02-14 19:40 UTC, thetif commented on web/src/pages/apd/activities/state-costs/StatePersonnel.test.js
> +    ).toEqual({ personnel: 'these are personnel', apdType: 'HITECH' });
you should use the APD_TYPE.HITECH const here

2023-02-15 16:49 UTC, jeromeleecms requested changes
@mirano-darren For the link to the SMDL letter, can you adjust it to open in a new tab instead of in the same window. This is the case for other external link through out the app (and you can't just back navigate to the APD).

2023-02-16 00:10 UTC, jeromeleecms approved these changes
Great - thanks for the quick fix. Good to go on my end.

2023-02-17 15:21 UTC, SGilliamA1M approved these changes
Verified that a HITECH APD has the old help text and MMIS APD has the new help text. 
Well done!

2023-02-17 15:53 UTC, merged