4612 [Feature] Create component for Conditions for Enhanced Funding
Enterprise-CMCS/eAPD pull request #4628
Opened 2023-03-21 21:03 UTC by thetif

Resolves #4612 

### Description
Adds the code for the form view of Conditions for Enhanced Funding

### Chromatic Link

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| the Conditions for Enhanced Funding page | the user clicks the "Review Standards and Conditions Regulation" link | the Standards and Conditions Help Drawer should open | jest |
| the Conditions for Enhanced Funding page | the Standards and Conditions Help Drawer is open and the user clicks close in the drawer | the help drawer should close | jest |
| the Conditions for Enhanced Funding page | the APD has no values | the form should show Qualification radio buttons with no values selected | jest |
| the Conditions for Enhanced Funding page | the APD has No Qualifications | the No radio button should be selected | jest |
| the Conditions for Enhanced Funding page | the APD has Yes Qualifications and a Justification | the Yes radio button should be selected and the Justification should display the Justification text | jest |
| the Conditions for Enhanced Funding page with no values | admin check is on |  the error message "Select an Enhanced Funding Qualification" should be displayed | jest |
| the Conditions for Enhanced Funding page with No Qualifications | admin check is on | no error messages should still be displayed | jest |
| the Conditions for Enhanced Funding page with Yes Qualifications | admin check is on | the error message "Provide an Enhanced Funding Justification" should be displayed | jest |

### Steps to manually verify this change

1. Open an MMIS APD
2. Open an Activity
3. Go to Conditions for Enhanced Funding
4. Verify that the page displays like the figma
5. Click the Review Standards and Conditions Regulation link
6. Verify that the Standards and Conditions Help Drawer opens
7. Verify that the text matches the ticket
8. Verify that clicking the Close button on the help drawer closes the drawer
9. Verify that selecting No works
10. Verify that selecting Yes opens the Justification text area
11. Verify that selecting No/Yes is saved by closing the APD and opening it again
12. Enter data in the Justification area
13. Verify that the Justification is saved by closing the APD and opening it again
14. Open the admin panel
15. Verify that no errors are displayed when the fields are filled out
16. Open another Activity
17. Verify that the error message is present when no Qualification has been selected
18. Verify that selecting No causes the error message to disappear
19. Verify that selecting Yes opens the Justification area and displays an error message for not Justification being present
20. Verify that entering data in the Justification area causes the error message to disappear

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [ ] Chromatic link added above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2023-03-22 20:10 UTC, tbolt requested changes
This code looks good and the component works fine. The adminCheck panel is working but it links to `/enhanced-funding` but the nav item is `/conditions`. I don't have a preference between the naming but they'll need to match.

2023-03-23 13:40 UTC, Sun-Mountain approved these changes
🚀

2023-03-27 21:57 UTC, thetif commented
@tbolt I switched them all to enchanced-funding, though I found out it would have been easier to just switch the adminCheck to conditions :D

2023-03-28 12:44 UTC, tbolt approved these changes

2023-03-28 13:31 UTC, amyd11 commented on web/src/components/StandardsAndConditionsHelpDrawer.js
Glad you made this it's own component since there's so much content in here

2023-03-28 17:01 UTC, mirano-darren approved these changes
Looks good to me, Nice job! 
| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|    the Conditions for Enhanced Funding page   |   values are entered in the fields   |   they are saved to the APD in mongo   |    ✅      |
| an APD with the Conditions for Enhanced Funding fields filled in | the page opens | the saved values should display |✅ |
| adminCheck is on | the fields are empty | the error messages should appear under the fields and in the adminCheck panel |✅ |
| adminCheck is open | the fields are filled in | there should be no error messages on the page or in the adminCheck panel |✅ |
| adminCheck is off | the fields are valid or invalid | no error messages are displayed |✅ |
| the Conditions for Enhanced Funding page | testing hyperlinks | Link goes to the correct page and opens in a new tab |✅ |

2023-03-28 18:38 UTC, jeromeleecms reviewed
Is there a way to adjust the width of the content under the "Yes" option? This area is really cramped (and the Figma has it extending all the way to the right border of the layout). 

Also, can we add one last bit of text after this: 

Describe how this activity will or WILL NOT support the Medicaid Standards and Conditions [42 CFR 433.112](https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-C/part-433/subpart-C/section-433.112). **Ensure all Standards and Conditions are addressed.** (bold added for emphasis and does not need to appear in the final copy)

2023-03-28 20:45 UTC, SGilliamA1M approved these changes
Changes look great. I agree with @jeromeleecms regarding making the width size bigger within the expanded container. @thetif I dropped you a note in Chromatic as well. One small typo in the help text. Everything else looks good!

2023-03-29 17:22 UTC, thetif commented
@jeromeleecms and @SGilliamA1M how do the changes look? If everything is good, I will merge.

2023-03-29 18:23 UTC, jeromeleecms approved these changes
Looks good!

2023-03-29 20:04 UTC, merged